[project]
name = "cid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "spacy>=3.8.11",
    "streamlit>=1.52.1",
    "textblob>=0.19.0",
]
